# green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codetonic-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codetonic
      version: v2
  template:
    metadata:
      labels:
        app: codetonic
        version: v2
    spec:
      containers:
      - name: codetonic
        image: anish2shukla/codetonic:v2
        ports:
        - containerPort: 80